import AppShowcase from '../components/AppShowcase';
import ExportCounter from '../components/ExportCounter';
import { screensFromGlob } from '../utils/screens';
import icon from '../assets/maestro/icon.png';

// Official brand color: Tesla Autopilot blue, the app's own accent.
const ACCENT_COLOR = '#2D7FF9';
const APP_STORE_URL = 'https://apps.apple.com/us/app/maestro-light-show-studio/id6803264666';

const screens = screensFromGlob(
  import.meta.glob('../assets/maestro/screens/*', { eager: true, import: 'default' })
);

export default function Maestro() {
  return (
    <AppShowcase
      name="Maestro"
      heading="Maestro - Light Show Studio"
      tagline="Drop in a song. Get a Tesla light show. Choreographed on your iPhone, iPad, or Mac, played on your car."
      icon={icon}
      accentColor={ACCENT_COLOR}
      meta={{
        title: 'Maestro – Tesla Light Show Studio for iPhone, iPad & Mac | Nick Molargik',
        description:
          'Maestro turns any song into a Tesla light show. On-device signal processing, a hardware-accurate fleet preview, a channel-level Sequence Editor on the Mac, and USB-ready exports. No AI, nothing uploaded.',
      }}
      appStoreUrl={APP_STORE_URL}
      requirements={['iOS 17+', 'iPadOS 17+', 'macOS 14+', 'Model S · 3 · X · Y · Cybertruck']}
      screens={screens}
      screensClassName="bg-gradient-to-b from-[#0b1220] via-[#0c1424] to-surface"
      afterScreens={
        <section aria-label="Exported show counter" className="bg-[#07090f] py-16 sm:py-20">
          <div className="mx-auto max-w-4xl px-6">
            <ExportCounter accentColor={ACCENT_COLOR} />
          </div>
        </section>
      }
      about={{
        title: 'Maestro — Your Tesla’s Light Show Studio',
        intro:
          'Drop in a song. Maestro listens to it the way a choreographer would, then writes a complete Tesla light show around what it hears: the beats, the key, the builds, the drops, the solos, even the quiet moments that deserve darkness. Preview it on a stage of hardware-accurate vehicles, fine-tune every channel in the Sequence Editor, then export the exact files the car wants.',
        sections: [
          {
            title: 'No AI. Just signal processing.',
            body: 'Maestro measures your music right on your device and choreographs from the math. Nothing is uploaded, nothing is generated by a model, and the same song with the same seed always produces the identical show. Do not like a take? Reroll it, or on the Mac right-click a single section and reroll just that passage.',
          },
          {
            title: 'Built for the actual hardware',
            body: 'Every Tesla lamp has a personality, and Maestro knows all of them. Headlights that ramp, signatures that snap, the Cybertruck’s pixel light bars, interior ambient strips, and the closures: mirrors that fold on the hush, windows that dance, falcon doors that open for the finale, a charge port that saves its rainbow for the last chorus. Command budgets and thermal limits are respected so the car never refuses your show.',
          },
          {
            title: 'See it before the driveway does',
            body: 'A live preview stage plays your show on Model S, Model 3, Model X, Model Y, and Cybertruck, including pre-refresh 3 and Y bodies with their real lamp responses. Build a fleet of up to 15 of each, arrange rows or a circle, and watch the light wash between cars. Presentation mode turns your iPad or Mac into the party screen.',
          },
          {
            title: 'One library, every device',
            body: 'Your shows sync through iCloud between your iPhone, iPad, and Mac. Choreograph on the couch, fine-tune in the Sequence Editor on your Mac, and export from whichever device is closest to the car.',
          },
          {
            title: 'Try it free',
            body: 'A finished sample show is included, and your first two exported shows are free. One purchase unlocks unlimited shows and unlimited exports on iPhone, iPad, and Mac, and the Sequence Editor on the Mac. No subscription. Yours forever, on all your devices.',
          },
        ],
        features: [
          {
            icon: '🎼',
            title: 'Song-Aware Choreography',
            description:
              'Verses breathe, choruses hit, drum solos flip through every lamp, and the finale lands exactly with the song. Every show ends dark, validated, and ready for the car.',
          },
          {
            icon: '🚗',
            title: 'Hardware-Accurate Fleet Preview',
            description:
              'Five body styles with real lamp physics, ramping channels, diffused pixel bars, beams that wash the pavement, and one shared light field across the whole stage.',
          },
          {
            icon: '🎛️',
            title: 'Sequence Editor (Mac)',
            description:
              'Every channel on a timeline. Move, stretch, add, and delete blocks, snap to the beat grid, and watch the selected fixture outline on every car that has it.',
          },
          {
            icon: '📼',
            title: 'USB-Ready Exports',
            description:
              'The exact .fseq and audio pair the car expects, validated against Tesla’s own rules. Save straight to a USB drive, AirDrop to your Mac, then open Toybox and schedule the show.',
          },
          {
            icon: '📱',
            title: 'Share-Ready Video',
            description:
              'Render the preview stage to video, including a vertical cut sized for TikTok, Reels, and Shorts.',
          },
          {
            icon: '🌍',
            title: 'Five Languages',
            description:
              'English, Spanish, German, Dutch, and Norwegian, with hardware-accurate previews in every one of them.',
          },
        ],
        footnote:
          'Maestro is an independent app and is not affiliated with or endorsed by Tesla, Inc. Tesla, Model S, Model 3, Model X, Model Y, and Cybertruck are trademarks of Tesla, Inc. A Tesla vehicle with light show support and a USB drive are required to play shows on a car.',
      }}
      jsonLd={{
        name: 'Maestro: Light Show Studio',
        applicationCategory: 'EntertainmentApplication',
        operatingSystem: 'iOS, iPadOS, macOS',
        inLanguage: ['en', 'es', 'de', 'nl', 'nb'],
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
        url: APP_STORE_URL,
      }}
    />
  );
}
